### ISSUE TITLE
BD的加固XML解析报错啊

### ISSUE THREAD

**Issue by IDrinkMoreWater** [DrizzleRisk/BUnpacker#1]
[>>>]       BUnpacker         [<<<]
[>>>]    code by Drizzle      [<<<]
[>>>]        2016.10          [<<<]
[*] Init env
[*] Target: x86
[---------------------------------------]
close failed in file object destructor:
IOError: [Errno 0] Error
[---------------------------------------]
[*] Get package info
Traceback (most recent call last):
  File "bunpacker.py", line 83, in <module>
    CheckEnv()
  File "bunpacker.py", line 44, in CheckEnv
    mfest = minidom.parseString(content)
  File "C:\Python27\lib\xml\dom\minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "C:\Python27\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by DrizzleRisk** [comment]
这个不是针对百度的

**Comment by IDrinkMoreWater** [comment]
嗯嗯,360的用drizzleDumper也能脱出来dex,但是转成jar的时候只有几kb,显示是Android系统的相关包,这个怎么回事

**Comment by DrizzleRisk** [comment]
drizzleDumper是dump所有匹配的dex了，包括系统的
数字可以用这个专版，会精准一些：链接:https://pan.baidu.com/s/1pKX3ZF9 密码:fpsx
